export const INGREDIENT_ADD = "INGREDIENT_ADD"
export const INGREDIENT_REMOVE = "INGREDIENT_REMOVE"
export const INGREDIENT_SET = "INGREDIENT_SET"
export const INGREDIENT_FETCH_FAILED = "INGREDIENT_FETCH_FAILED"

export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL"
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS"
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START"

export const PURCHASE_INIT = "PURCHASE_INIT"

export const FETCH_ORDER_START = "FETCH_ORDER_START"
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS"
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL"
